// This file was generated by current env while u run application.
// Do not edit this file as changes may cause incorrect behavior and will be lost
// once the code is regenerated.

import Config from 'react-native-config';

export const APP_BUILD_VERSION = '1.0.0.2023.10.16.11.07';

export const {
  API_URL,
  APP_DISPLAY_NAME,
  VERSION_NAME,
  BUNDLE_IDENTIFIER,
  DEFAULT_FALLBACK_LNG_I18n,
  PRIVATE_KEY_STORAGE,
  WORKSPACE_NAME,
  SCHEME_SUFFIX,
  ASSETCATALOG_COMPILER_APPICON_NAME,
  DEBUG_PROVISIONING_PROFILE,
  PUBLISH_PROVISIONING_PROFILE,
  APPLE_DEVELOPMENT_TEAM,
  IOS_VERSION_CODE,
  FLAVOR,
  ANDROID_VERSION_CODE,
} = Config as Record<string, string>;
